name: apm
description: Application Performance Monitoring
version: 0.0.1
homepage: https://github.com/PlugFox/apm

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  crypto: ^3.0.2
  protobuf: ^2.1.0
  meta: ^1.3.0
  web_socket_channel: ^2.3.0
  stack_trace: ^1.11.0

dev_dependencies:
  lints: ^2.0.0
  test: any